! Base FRR Config
router ospf
 ospf router-id 10.99.2.2
 network 10.99.2.0/30 area 0
 redistribute babel

router babel
 babel diversity
 redistribute ospf
 network eth0.24
 network eth0.900

interface eth0.24
 babel type wireless
 no babel split-horizon
 babel channel 1
 babel rxcost 250
 babel hello-interval 1000
 babel update-interval 4000
 babel enable-timestamps
 babel max-rtt-penalty 150

interface eth0.900
 babel type wireless
 no babel split-horizon
 babel channel 2
 babel rxcost 500
 babel hello-interval 1000
 babel update-interval 4000
 babel enable-timestamps
 babel max-rtt-penalty 150
