! Base FRR Config
interface eth0.99
 ip pim

router ospf
 ospf router-id 10.99.2.2
 network 10.99.2.0/30 area 0
 redistribute babel
 redistribute connected

router babel
 babel diversity
 redistribute ipv4 ospf
 network eth0.900
 network eth0.24

interface eth0.900
 ip pim
 babel wireless
 no babel split-horizon
 babel channel 1
 babel rxcost 400
 babel hello-interval 3000
 babel update-interval 12000
 babel enable-timestamps
 babel max-rtt-penalty 150

interface eth0.24
 ip pim
 babel wireless
 no babel split-horizon
 babel channel 2
 babel rxcost 250
 babel hello-interval 3000
 babel update-interval 12000
 babel enable-timestamps
 babel max-rtt-penalty 150
