network:
  version: 2
  ethernets:
    end0:
      dhcp4: true
  vlans:
    end0.99:
      id: 99
      link: end0
      addresses: [10.99.1.2/30]
    end0.900:
      id: 900
      link: end0
      addresses: [10.0.0.1/29]
    end0.24:
      id: 24
      link: end0
      addresses: [10.0.0.9/29]
